AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB cache table for language detection results for Project Lenie'

Parameters:
  ProjectCode:
    Type: String
    Default: lenie
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, qa, qa2, qa3, prod]
    Description: Environment name

Conditions:
  IsProduction: !Or
    - !Equals [!Ref Environment, prod]
    - !Equals [!Ref Environment, qa]
    - !Equals [!Ref Environment, qa2]
    - !Equals [!Ref Environment, qa3]

Resources:
  CacheLanguageTable:
    Type: AWS::DynamoDB::Table
    # Retain prevents accidental table deletion during stack operations
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      # Hardcoded to match existing table name (CF import requirement)
      TableName: lenie_cache_language
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: hash
          AttributeType: S
        - AttributeName: provider
          AttributeType: S
      KeySchema:
        - AttributeName: hash
          KeyType: HASH
        - AttributeName: provider
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !If [IsProduction, true, false]
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectCode

  # SSM Parameter exports
  CacheLanguageTableNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/${ProjectCode}/${Environment}/dynamodb/cache-language/name'
      Type: String
      Value: !Ref CacheLanguageTable
      Description: 'DynamoDB cache-language table name for Project Lenie'
      Tags:
        Environment: !Ref Environment
        Project: !Ref ProjectCode

  CacheLanguageTableArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/${ProjectCode}/${Environment}/dynamodb/cache-language/arn'
      Type: String
      Value: !GetAtt CacheLanguageTable.Arn
      Description: 'DynamoDB cache-language table ARN for Project Lenie'
      Tags:
        Environment: !Ref Environment
        Project: !Ref ProjectCode
