AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lambda Layer with psycopg2 PostgreSQL adapter for Project Lenie'

Parameters:
  ProjectCode:
    Type: String
    Default: lenie
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, qa, qa2, qa3, prod]
    Description: Environment name
  LayerCodeBucket:
    Type: String
    Description: S3 bucket containing the layer code ZIP artifact
  LayerCodeS3Key:
    Type: String
    Default: layers/psycopg2_new_layer.zip
    Description: S3 key for the layer code ZIP artifact
  LayerCodeVersion:
    Type: String
    Default: '1'
    Description: Version identifier — change this to force a new layer version when S3 key stays the same

Conditions:
  IsProduction: !Or
    - !Equals [!Ref Environment, prod]
    - !Equals [!Ref Environment, qa]
    - !Equals [!Ref Environment, qa2]
    - !Equals [!Ref Environment, qa3]

Resources:
  # Lambda Layer — stateless resource, recreated on every deploy (no DeletionPolicy needed)
  Psycopg2Layer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: psycopg2_new_layer
      Description: !Sub 'Lambda Layer with psycopg2 PostgreSQL adapter for Project Lenie (v${LayerCodeVersion})'
      CompatibleRuntimes:
        - python3.11
      Content:
        S3Bucket: !Ref LayerCodeBucket
        S3Key: !Ref LayerCodeS3Key

  # SSM Parameter exports — layer ARN includes version number for consuming Lambda functions
  Psycopg2LayerArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/${ProjectCode}/${Environment}/lambda/layers/psycopg2/arn'
      Type: String
      Value: !Ref Psycopg2Layer
      Description: 'Lambda Layer ARN (with version) for psycopg2 layer for Project Lenie'
      Tags:
        Environment: !Ref Environment
        Project: !Ref ProjectCode
