AWSTemplateFormatVersion: 2010-09-09
Description: Template for Application launch template

Parameters:
  ProjectCode:
    Type: String
    Default: lenie
    Description: Project code for resource naming and tagging
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,20}$
  Environment:
    Type: String
    Default: dev
    Description: Deployment environment
    AllowedValues:
      - dev
      # Post-MVP: add prod, qa as needed
  Component:
    Description: Name of the component
    Type: String
    AllowedPattern: ^[a-z][a-zA-Z0-9-]{3,15}$
  ImageId:
    Description: Id of the AMI with Application
    Type: AWS::EC2::Image::Id
  InstanceType:
    Description: Type of instance
    Type: String
    Default: t2.micro

Resources:
  ApplicationLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref ImageId
        InstanceType: !Ref  InstanceType
        Monitoring:
          Enabled: true
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub ${ProjectCode}-${Environment}-${Component}-application-instance
              - Key: Environment
                Value: !Ref Environment
              - Key: Project
                Value: !Ref ProjectCode
      TagSpecifications:
        - ResourceType: launch-template
          Tags:
            - Key: Environment
              Value: !Ref Environment
            - Key: Project
              Value: !Ref ProjectCode

  ApplicationLaunchTemplateParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${ProjectCode}-${Environment}-${Component} Application Launch Template Id
      Tier: Standard
      Name: !Sub /${ProjectCode}/${Environment}/${Component}/application-launch-template/id
      Value: !Ref ApplicationLaunchTemplate
      Tags:
        Name: !Sub ${ProjectCode}-${Environment}-${Component}-application-launch-template-id-param
        Environment: !Ref Environment
        Project: !Ref ProjectCode

  ApplicationLaunchTemplateLatestVersionParam:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Description: !Sub Stores ${ProjectCode}-${Environment}-${Component} Application Launch Template Latest Version No.
      Tier: Standard
      Name: !Sub /${ProjectCode}/${Environment}/${Component}/application-launch-template/latest-version
      Value: !GetAtt ApplicationLaunchTemplate.LatestVersionNumber
      Tags:
        Name: !Sub ${ProjectCode}-${Environment}-${Component}-application-launch-template-latest-version-param
        Environment: !Ref Environment
        Project: !Ref ProjectCode

Outputs:
  ApplicationLaunchTemplateId:
    Description: The ID of the Application Launch Template
    Value: !Ref ApplicationLaunchTemplate
  ApplicationLaunchTemplateIdParamName:
    Description: The name of the SSM parameter where the Id of the Application Launch Template is stored
    Value: !Ref ApplicationLaunchTemplateParam
  ApplicationLaunchTemplateLatestVersionParamName:
    Description: The name of the SSM parameter where the latest version of the Application Launch Template is stored
    Value: !Ref ApplicationLaunchTemplateLatestVersionParam
