Parameters:
  ProjectCode:
    Type: String
    Default: lenie
    Description: Project code for resource naming and tagging
  Environment:
    Type: String
    Default: dev
    Description: Deployment environment
    AllowedValues:
      - dev
      # Post-MVP: add prod, qa as needed
  VPCId:
    Description: The VPC Id where the RDS instance will be deployed
    Type: AWS::SSM::Parameter::Value<String>
  RDSPasswordSecretArn:
    Type: String
    Description: 'ARN of the Secret in AWS Secrets Manager that holds the RDS master user password'
  DataSubnetA:
    Description: Reference of the DataSubnetA from the SSM
    Type: AWS::SSM::Parameter::Value<String>
  DataSubnetB:
    Description: Reference of the DataSubnetB from the SSM
    Type: AWS::SSM::Parameter::Value<String>
  SnapshotIdentifier:
    Type: String
    Description: 'ARN of the DB snapshot (optional)'
    Default: ''

Conditions:
  HasSnapshot: !Not [!Equals [!Ref SnapshotIdentifier, '']]


Resources:
  MyDB:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBName: !If
        - HasSnapshot
        - !Ref AWS::NoValue
        - !Sub 'lenieTmp${Environment}'
      DBSnapshotIdentifier: !If
        - HasSnapshot
        - !Ref SnapshotIdentifier
        - !Ref AWS::NoValue
      Engine: postgres
      MasterUsername: !Sub '{{resolve:secretsmanager:${RDSPasswordSecretArn}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${RDSPasswordSecretArn}:SecretString:password}}'
      AllocatedStorage: '20'
      DBInstanceClass: db.t3.micro
      DBSubnetGroupName: !Ref DbSubnetGroup
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      PubliclyAccessible: false
      MultiAZ: false
      VPCSecurityGroups:
            - !GetAtt MyDatabaseSecurityGroup.GroupId
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectCode

  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub Subnet group for ${ProjectCode}-${Environment}-db instance
      SubnetIds:
        - !Ref DataSubnetA
        - !Ref DataSubnetB
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectCode


  MyDatabaseSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security Group for RDS DB Instance.
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '5432'
          ToPort: '5432'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${ProjectCode}-${Environment}-rds-sg'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectCode
