AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket for website content storage for Project Lenie'

Parameters:
  ProjectCode:
    Type: String
    Default: lenie
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, qa, qa2, qa3, prod]
    Description: Environment name

Conditions:
  IsProduction: !Or
    - !Equals [!Ref Environment, prod]
    - !Equals [!Ref Environment, qa]
    - !Equals [!Ref Environment, qa2]
    - !Equals [!Ref Environment, qa3]

Resources:
  # S3 bucket for website content storage
  # Recreate strategy — no DeletionPolicy needed (default Delete is intentional)
  WebsiteContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectCode}-${Environment}-website-content'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        # Versioning enabled in production environments as a safety net
        Status: !If [IsProduction, Enabled, Suspended]
      # LoggingConfiguration intentionally omitted — accepted cost trade-off for $8/month budget hobby project
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectCode

  # Enforce TLS-only access to the bucket
  WebsiteContentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteContentBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyNonSSLRequests
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !GetAtt WebsiteContentBucket.Arn
              - !Sub '${WebsiteContentBucket.Arn}/*'
            Condition:
              Bool:
                aws:SecureTransport: 'false'

  # SSM Parameter exports
  WebsiteContentBucketNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/${ProjectCode}/${Environment}/s3/website-content/name'
      Type: String
      Value: !Ref WebsiteContentBucket
      Description: 'S3 website-content bucket name for Project Lenie'
      Tags:
        Environment: !Ref Environment
        Project: !Ref ProjectCode

  WebsiteContentBucketArnParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/${ProjectCode}/${Environment}/s3/website-content/arn'
      Type: String
      Value: !GetAtt WebsiteContentBucket.Arn
      Description: 'S3 website-content bucket ARN for Project Lenie'
      Tags:
        Environment: !Ref Environment
        Project: !Ref ProjectCode
