AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create a Passwords etc for Lenie application

Parameters:
  ProjectCode:
    Type: String
    Default: lenie
    Description: Project code for resource naming and tagging
  Environment:
    Type: String
    Default: dev
    Description: Deployment environment
    AllowedValues:
      - dev
      # Post-MVP: add prod, qa as needed
  DBMasterUserPassword:
    Type: String
    Description: 'RDS Master User Password'
    NoEcho: true

Resources:
  RDSPasswordSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub '/${ProjectCode}/${Environment}/rds/password'
      Description: 'Secret that holds the RDS master user password'
      SecretString: !Sub |
        {
          "username": "lenie",
          "password": "${DBMasterUserPassword}"
        }
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectCode
