AWSTemplateFormatVersion: '2010-09-09'
Description: Test template for security groups

Parameters:
  ProjectCode:
    Type: String
    Default: lenie
    Description: Project code for resource naming and tagging
  Environment:
    Type: String
    Default: dev
    Description: Deployment environment
    AllowedValues:
      - dev
      # Post-MVP: add prod, qa as needed

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access from specific IP address
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 31.183.191.172/32
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 31.183.191.173/32
      Tags:
        - Key: Name
          Value: !Sub '${ProjectCode}-${Environment}-ssh-sg'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectCode
