AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda function that processes messages from SQS queue and writes them to RDS PostgreSQL for Project Lenie

Parameters:
  ProjectCode:
    Type: String
    Default: lenie
    Description: Project code for resource naming and tagging
  Environment:
    Type: String
    Default: dev
    Description: Deployment environment
    AllowedValues:
      - dev
      # Post-MVP: add prod, qa as needed
  SubnetId1:
    Type: String
    Description: First subnet ID for Lambda VPC configuration
    AllowedPattern: 'subnet-[a-f0-9]+'
  SubnetId2:
    Type: String
    Description: Second subnet ID for Lambda VPC configuration
    AllowedPattern: 'subnet-[a-f0-9]+'
  SubnetId3:
    Type: String
    Description: Third subnet ID for Lambda VPC configuration
    AllowedPattern: 'subnet-[a-f0-9]+'
  SecurityGroupId:
    Type: String
    Description: Security group ID allowing PostgreSQL access
    AllowedPattern: 'sg-[a-f0-9]+'
  LenieAllLayerArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/lenie/dev/lambda/layers/lenie-all/arn'
    Description: SSM path for lenie-all Lambda layer ARN
  Psycopg2LayerArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/lenie/dev/lambda/layers/psycopg2/arn'
    Description: SSM path for psycopg2 Lambda layer ARN
  PostgresqlHost:
    Type: String
    Description: RDS PostgreSQL endpoint hostname
  PostgresqlDatabase:
    Type: String
    Default: lenie
    Description: PostgreSQL database name
  PostgresqlPort:
    Type: String
    Default: '5432'
    Description: PostgreSQL port number
  SqsDocumentsUrl:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/lenie/dev/sqs/documents/url'
    Description: SSM path for SQS documents queue URL

Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectCode}-${Environment}-sqs-to-rds-lambda'
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaExecutionRole.Arn
      Layers:
        - !Sub 'arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV3-python311-x86_64:6'
        - !Ref LenieAllLayerArn
        - !Ref Psycopg2LayerArn
      Code:
        S3Bucket: !Sub '{{resolve:ssm:/${ProjectCode}/${Environment}/s3/cloudformation/name}}'
        S3Key: !Sub '${ProjectCode}-${Environment}-sqs-into-rds.zip'
      Environment:
        Variables:
          AWS_QUEUE_URL_ADD: !Ref SqsDocumentsUrl
          POSTGRESQL_DATABASE: !Ref PostgresqlDatabase
          POSTGRESQL_HOST: !Ref PostgresqlHost
          POSTGRESQL_PASSWORD: !Sub '{{resolve:secretsmanager:/${ProjectCode}/${Environment}/rds/password:SecretString:password}}'
          POSTGRESQL_PORT: !Ref PostgresqlPort
          POSTGRESQL_USER: !Sub '{{resolve:secretsmanager:/${ProjectCode}/${Environment}/rds/password:SecretString:username}}'
      Timeout: 900
      MemorySize: 128
      VpcConfig:
        SubnetIds:
          - !Ref SubnetId1
          - !Ref SubnetId2
          - !Ref SubnetId3
        SecurityGroupIds:
          - !Ref SecurityGroupId
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectCode


  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - sqs:DeleteMessage
                  - sqs:ReceiveMessage
                  - sqs:GetQueueAttributes
                Resource: !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${ProjectCode}*'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectCode
