AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ProjectCode:
    Type: String
    Default: lenie
    Description: Project code for resource naming and tagging
  Environment:
    Type: String
    Default: dev
    Description: Deployment environment
    AllowedValues:
      - dev
      # Post-MVP: add prod, qa as needed

Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectCode}-${Environment}-sqs-to-rds-lambda'
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaExecutionRole.Arn
      Layers:
        - arn:aws:lambda:us-east-1:017000801446:layer:AWSLambdaPowertoolsPythonV3-python311-x86_64:6
        - arn:aws:lambda:us-east-1:008971653395:layer:lenie_all_layer:1
        - arn:aws:lambda:us-east-1:008971653395:layer:psycopg2_new_layer:1
      Code:
        S3Bucket: !Sub '{{resolve:ssm:/${ProjectCode}/${Environment}/s3/cloudformation/name}}'
        S3Key: !Sub '${ProjectCode}-${Environment}-sqs-to-db.zip'
      Environment:
        Variables:
          AWS_QUEUE_URL_ADD: https://sqs.us-east-1.amazonaws.com/008971653395/lenie_websites
          POSTGRESQL_DATABASE: lenie
          POSTGRESQL_HOST: lenie-dev.c9k28ukqsclc.us-east-1.rds.amazonaws.com
          POSTGRESQL_PASSWORD: change_me
          POSTGRESQL_PORT: 5432
          POSTGRESQL_USER: postgres

      Timeout: 900
      MemorySize: 128
      VpcConfig:
        SubnetIds:
          - subnet-065769ce9d50381e3
          - subnet-020824bbcbcb05271
          - subnet-05b4d47b482c89936
        SecurityGroupIds:
          - sg-0d3882a9806ec2a9c
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectCode


  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - sqs:DeleteMessage
                  - sqs:ReceiveMessage
                  - sqs:GetQueueAttributes
                Resource: "*"
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectCode
