AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for lenie-dev-url-add Lambda function'

Parameters:
  ProjectCode:
    Type: String
    Default: lenie
    Description: Project code

  Environment:
    Type: String
    Default: dev
    Description: Deployment environment
    AllowedValues:
      - dev
      # Post-MVP: add prod, qa as needed

  SqsDocumentsUrl:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/lenie/dev/sqs/documents/url'
    Description: SSM path for SQS documents queue URL

  # IMPORTANT: SqsDocumentsQueueName must match the queue referenced by SqsDocumentsUrl (SSM).
  # If the SSM parameter is updated to point to a different queue, update this value as well.
  # When sqs-documents.yaml stack is deployed, it will overwrite SSM to point to lenie-dev-documents;
  # update the parameter file value accordingly to avoid IAM permission mismatch.
  SqsDocumentsQueueName:
    Type: String
    AllowedPattern: '[a-zA-Z0-9_-]+'
    Description: Name of the SQS documents queue for IAM policy scoping

  timestamp:
    Type: String
    Description: Timestamp to force Lambda function update

Resources:
  LenineUrlAddLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Sub '${ProjectCode}-${Environment}-url-add'
      Handler: 'lambda_function.lambda_handler'
      Role: !GetAtt LambdaExecutionRole.Arn
      LoggingConfig:
        LogFormat: 'JSON'
        ApplicationLogLevel: 'INFO'
        SystemLogLevel: 'INFO'
      Layers:
        - arn:aws:lambda:us-east-1:017000801446:layer:AWSLambdaPowertoolsPythonV3-python311-x86_64:6
      Code:
        S3Bucket: !Sub '{{resolve:ssm:/${ProjectCode}/${Environment}/s3/cloudformation/name}}'
        S3Key: !Sub '${ProjectCode}-${Environment}-url-add.zip'

      Runtime: 'python3.11'
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          LOG_LEVEL: 'INFO'
          AWS_QUEUE_URL_ADD: !Ref SqsDocumentsUrl
          BUCKET_NAME: !Sub '${ProjectCode}-${Environment}-website-content'
          DYNAMODB_TABLE_NAME: lenie_dev_documents
          TIMESTAMP: !Ref timestamp
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectCode

  LenineUrlAddLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '/aws/lambda/${LenineUrlAddLambdaFunction}'
      RetentionInDays: 7
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectCode

  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: LambdaBasicExecution2
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
        - PolicyName: SendDataToSQS
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource: !Sub "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${SqsDocumentsQueueName}"
        - PolicyName: S3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource:
                  - !Sub "arn:aws:s3:::${ProjectCode}-${Environment}-website-content/*"
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:BatchWriteItem
                Resource:
                  - Fn::ImportValue: !Sub "${ProjectCode}-${Environment}-dynamodb-documents-TableArn"
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectCode

  UrlAddApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: !Sub '${ProjectCode}_${Environment}_add_from_chrome_extension'
      Description: 'API for Chrome extension "Lenie AI assistant"'
      EndpointConfiguration:
        Types:
          - REGIONAL
      ApiKeySourceType: HEADER
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectCode

  ApiKey:
    Type: 'AWS::ApiGateway::ApiKey'
    Properties:
      Name: !Sub '${ProjectCode}-${Environment}-chrome-extension-key'
      Description: 'API Key for Chrome extension'
      Enabled: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectCode

  UsagePlan:
    Type: 'AWS::ApiGateway::UsagePlan'
    Properties:
      ApiStages:
        - ApiId: !Ref UrlAddApi
          Stage: !Ref ApiStage
      Description: 'Usage plan for Chrome extension API'
      UsagePlanName: !Sub '${ProjectCode}-${Environment}-chrome-extension-plan'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref ProjectCode

  UsagePlanKey:
    Type: 'AWS::ApiGateway::UsagePlanKey'
    Properties:
      KeyId: !Ref ApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

  UrlAddResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref UrlAddApi
      ParentId: !GetAtt UrlAddApi.RootResourceId
      PathPart: 'url_add'


  UrlAddMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: !Ref UrlAddApi
      ResourceId: !Ref UrlAddResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LenineUrlAddLambdaFunction.Arn}/invocations'
        TimeoutInMillis: 29000
        ContentHandling: CONVERT_TO_TEXT
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: 'Empty'

  UrlAddOptionsMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: !Ref UrlAddApi
      ResourceId: !Ref UrlAddResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  ApiStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      DeploymentId: !Ref ApiDeployment
      RestApiId: !Ref UrlAddApi
      StageName: 'v1'


  ApiDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn:
      - UrlAddMethod
      - UrlAddOptionsMethod
    Properties:
      RestApiId: !Ref UrlAddApi

  LambdaApiPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref LenineUrlAddLambdaFunction
      Principal: 'apigateway.amazonaws.com'
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${UrlAddApi}/*/*/*'


Outputs:
  ApiEndpoint:
    Description: "API Gateway URL"
    Value: !Sub 'https://${UrlAddApi}.execute-api.${AWS::Region}.amazonaws.com/v1/url_add'
  ApiKeyID:
    Description: "API Key ID"
    Value: !Ref ApiKey
